export type Page =
  | 'landing'
  | 'login'
  | 'kyc'
  | 'rider-dashboard'
  | 'workscore'
  | 'ev-financing'
  | 'financing-application'
  | 'repayments'
  | 'ownership'
  | 'lender-login'
  | 'lender-dashboard'
  | 'applications'
  | 'application-details'
  | 'riders'
  | 'approved'
  | 'lender-repayments'
  | 'reports'
  | 'settings'

export type NavigateFn = (page: Page) => void
